In [1]:
from pycolab import ascii_art
from pycolab.prefab_parts import sprites as prefab_sprites

import numpy as np
import pycolab
import matplotlib.pyplot as plt
%matplotlib inline

# Introduction

# Implementations

### Environments

#### 1. Blocking Maze

In [2]:
GAME_ART = ['###########',
            '#         #',
            '#         #',
            '#         #',
            '######### #',
            '#         #',
            '#   P     #',
            '###########']


def make_game():
    """Builds and returns a four-rooms game."""
    return ascii_art.ascii_art_to_game(GAME_ART, what_lies_beneath=' ',sprites={'P': PlayerSprite})


class PlayerSprite(prefab_sprites.MazeWalker):
    """A `Sprite` for our player.
    This `Sprite` ties actions to going in the four cardinal directions. If we
    reach a magical location (in this example, (4, 3)), the agent receives a
    reward of 1 and the epsiode terminates.
    """

    def __init__(self, corner, position, character):
        """Inform superclass that we can't walk through walls."""
        super(PlayerSprite, self).__init__(
            corner, position, character, impassable='#')
    


    def update(self, actions, board, layers, backdrop, things, the_plot):
        del layers, backdrop, things   # Unused.

        # Apply motion commands.
        if actions == 0:    # walk upward?
            self._north(board, the_plot)
        elif actions == 1:  # walk downward?
            self._south(board, the_plot)
        elif actions == 2:  # walk leftward?
            self._west(board, the_plot)
        elif actions == 3:  # walk rightward?
            self._east(board, the_plot)

        # See if we've found the mystery spot.
        magical_location = (1, 9)
        if self.position == magical_location:
            the_plot.add_reward(1.0)
            the_plot.terminate_episode()

In [3]:
game = make_game()
obs, reward, gamma = game.its_showtime();
obs, reward, gamma = game.play(5000)
state = np.array(obs.layers['P'], dtype=np.float)
print(state)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 2. Shortcut Maze

### Dyna-Q Algorithm

In [ ]:
def dynaQ():
    
    
    
    return

# Experiments

# How dows Dyna-Q relate to Experience Replay ?

# Conclusion